export interface AudioInstrumentOption {
  key: string;
  label: string;
}

// Stable public taxonomy adapted from the AudioSet ontology (CC BY-SA 4.0).
// The private pipeline maps YAMNet labels into these keys.
export const AUDIO_INSTRUMENT_OPTIONS: readonly AudioInstrumentOption[] = [
  { key: 'piano', label: 'ピアノ' },
  { key: 'electric_piano', label: 'エレクトリックピアノ' },
  { key: 'organ', label: 'オルガン' },
  { key: 'harpsichord', label: 'チェンバロ' },
  { key: 'guitar', label: 'ギター' },
  { key: 'acoustic_guitar', label: 'アコースティックギター' },
  { key: 'electric_guitar', label: 'エレキギター' },
  { key: 'bass_guitar', label: 'ベース' },
  { key: 'steel_guitar', label: 'スティールギター' },
  { key: 'ukulele', label: 'ウクレレ' },
  { key: 'banjo', label: 'バンジョー' },
  { key: 'mandolin', label: 'マンドリン' },
  { key: 'zither', label: 'ツィター' },
  { key: 'violin', label: 'バイオリン' },
  { key: 'viola', label: 'ビオラ' },
  { key: 'cello', label: 'チェロ' },
  { key: 'double_bass', label: 'コントラバス' },
  { key: 'bowed_strings', label: '擦弦楽器' },
  { key: 'string_section', label: 'ストリングス' },
  { key: 'harp', label: 'ハープ' },
  { key: 'flute', label: 'フルート' },
  { key: 'clarinet', label: 'クラリネット' },
  { key: 'saxophone', label: 'サックス' },
  { key: 'oboe', label: 'オーボエ' },
  { key: 'bassoon', label: 'ファゴット' },
  { key: 'recorder', label: 'リコーダー' },
  { key: 'trumpet', label: 'トランペット' },
  { key: 'trombone', label: 'トロンボーン' },
  { key: 'brass', label: 'ブラス' },
  { key: 'french_horn', label: 'ホルン' },
  { key: 'accordion', label: 'アコーディオン' },
  { key: 'harmonica', label: 'ハーモニカ' },
  { key: 'bagpipes', label: 'バグパイプ' },
  { key: 'didgeridoo', label: 'ディジュリドゥ' },
  { key: 'shofar', label: 'ショファル' },
  { key: 'theremin', label: 'テルミン' },
  { key: 'drum_kit', label: 'ドラム' },
  { key: 'drums', label: '太鼓' },
  { key: 'snare_drum', label: 'スネアドラム' },
  { key: 'bass_drum', label: 'バスドラム' },
  { key: 'timpani', label: 'ティンパニ' },
  { key: 'tabla', label: 'タブラ' },
  { key: 'percussion', label: 'パーカッション' },
  { key: 'cymbal', label: 'シンバル' },
  { key: 'hi_hat', label: 'ハイハット' },
  { key: 'tambourine', label: 'タンバリン' },
  { key: 'maraca', label: 'マラカス' },
  { key: 'gong', label: 'ゴング' },
  { key: 'mallet_percussion', label: '鍵盤打楽器' },
  { key: 'marimba_xylophone', label: 'マリンバ／木琴' },
  { key: 'glockenspiel', label: 'グロッケン' },
  { key: 'vibraphone', label: 'ビブラフォン' },
  { key: 'steelpan', label: 'スティールパン' },
  { key: 'synthesizer', label: 'シンセサイザー' },
  { key: 'drum_machine', label: 'ドラムマシン' },
  { key: 'sampler', label: 'サンプラー' },
  { key: 'orchestra', label: 'オーケストラ' },
] as const;

export const AUDIO_INSTRUMENT_LABELS = new Map(
  AUDIO_INSTRUMENT_OPTIONS.map(option => [option.key, option.label]),
);
