import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export interface AutoPlaySession {
  id: string;
  startedAt: number;
  rootSeedId: number;
  autoGeneratedCount: number;
  autoPlayedCount: number;
  autoCompletedCount: number;
  autoSkippedCount: number;
  manualOverrideCount: number;
  consecutiveSkips: number;
  strategyVersion: string;
}

interface AutoPlaySessionState {
  session: AutoPlaySession | null;
  startSession: (rootSeedId: number) => void;
  recordAutoQueueAdded: (count: number) => void;
  recordAutoPlaybackStarted: () => void;
  recordAutoPlaybackOutcome: (outcome: 'complete' | 'skip' | 'neutral') => void;
  recordManualOverride: () => void;
  clearSession: () => void;
}

const SESSION_STORAGE_KEY = 'diva-autoplay-session-v1';
const STRATEGY_VERSION = 'fixed-known-unknown-v1';

function createSession(rootSeedId: number): AutoPlaySession {
  const now = Date.now();
  return {
    id: `${now}-${Math.random().toString(36).slice(2, 10)}`,
    startedAt: now,
    rootSeedId,
    autoGeneratedCount: 0,
    autoPlayedCount: 0,
    autoCompletedCount: 0,
    autoSkippedCount: 0,
    manualOverrideCount: 0,
    consecutiveSkips: 0,
    strategyVersion: STRATEGY_VERSION,
  };
}

export const useAutoPlaySessionStore = create<AutoPlaySessionState>()(
  persist(
    (set) => ({
      session: null,
      startSession: (rootSeedId) => set({ session: createSession(rootSeedId) }),
      recordAutoQueueAdded: (count) => set(state => state.session ? {
        session: {
          ...state.session,
          autoGeneratedCount: state.session.autoGeneratedCount + Math.max(0, Math.floor(count)),
        },
      } : state),
      recordAutoPlaybackStarted: () => set(state => state.session ? {
        session: { ...state.session, autoPlayedCount: state.session.autoPlayedCount + 1 },
      } : state),
      recordAutoPlaybackOutcome: (outcome) => set(state => {
        if (!state.session || outcome === 'neutral') return state;
        if (outcome === 'complete') {
          return {
            session: {
              ...state.session,
              autoCompletedCount: state.session.autoCompletedCount + 1,
              consecutiveSkips: 0,
            },
          };
        }
        return {
          session: {
            ...state.session,
            autoSkippedCount: state.session.autoSkippedCount + 1,
            consecutiveSkips: state.session.consecutiveSkips + 1,
          },
        };
      }),
      recordManualOverride: () => set(state => state.session ? {
        session: { ...state.session, manualOverrideCount: state.session.manualOverrideCount + 1 },
      } : state),
      clearSession: () => set({ session: null }),
    }),
    { name: SESSION_STORAGE_KEY },
  ),
);
